### PR TITLE
judge: pass `result` to checkers

### PR DESCRIPTION
**Pull request by Riolku**

### CODE REVIEW

**Review by Xyene — CHANGES_REQUESTED** [review]
If we're going to do this, let's just pass the whole result object

**Comment by Riolku** [comment]
Hm.. but keep the rest of the kwargs for backward compatability?

**Comment by Xyene** [comment]
Yes

**Comment by Riolku** [comment]
Passing `result` now, updated tests and commit message.

**Review by kiritofeng — APPROVED** [review]
LGTM

**Comment by Riolku** [comment]
Seems `black` is bricked right now. I'll check back later tonight.

**Review by Xyene — APPROVED** [review]
LGTM, thanks

**Pull request merged**
