### PR TITLE
executors/OBJC: fix executor

### PR DESCRIPTION
**Pull request by int-y1**
* This executor calls `prctl` with 23.
* This executor tries to traverse `~/GNUstep`, but this directory doesn't exist. I did `RecursiveDir('~')` to work around this issue.
* Apparently, `initialize(cls)` doesn't run. I wrote `autoconfig(cls)` to do the setup.
* Afterwards, add `apt-get install make gnustep-devel` to the DMOJ dockerfile.

### CODE REVIEW

**Review by quantum5 — APPROVED** [review]

**Comment by quantum5** [comment]
ok to test

**Comment by Xyene** [comment]
> This executor tries to traverse ~/GNUstep, but this directory doesn't exist. I did `RecursiveDir('~')` to work around this issue.

In what way does it fail if you don't allow `~`, and allow `~/GNUstep` instead?

**Comment by int-y1** [comment]
> > This executor tries to traverse ~/GNUstep, but this directory doesn't exist. I did `RecursiveDir('~')` to work around this issue.
> 
> In what way does it fail if you don't allow `~`, and allow `~/GNUstep` instead?

```
0.414 Testing OBJC:   Failed self-test                                                                                                                                                                
0.500   Attempted:                                                                                                                                                                                    
0.502     gcc: /usr/bin/gcc
...
0.502   Errors:
0.502     Traceback (most recent call last):
0.502       File "/judge/dmoj/executors/base_executor.py", line 337, in run_self_test
0.502         executor = cls(cls.test_name, utf8bytes(cls.test_program))
0.502                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.502       File "/judge/dmoj/executors/compiled_executor.py", line 63, in __call__
0.502         obj.compile()
0.502       File "/judge/dmoj/executors/compiled_executor.py", line 212, in compile
0.502         self.warning = self.get_compile_output(process)
0.502                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.502       File "/judge/dmoj/executors/compiled_executor.py", line 194, in get_compile_output
0.502         self.handle_compile_error(output)
0.502       File "/judge/dmoj/executors/compiled_executor.py", line 205, in handle_compile_error
0.502         raise CompileError(output)
0.502     dmoj.error.CompileError: cc1obj: error: /home/judge/GNUstep/Library/Headers: Permission denied
```

**Review by Xyene — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
